'use strict';

module.exports = {
    Addresses: require('./Addresses'),
    Admins: require('./Admins'),
    BugReports: require('./BugReports'),
    BugReportComments: require('./BugReportComments'),
    Contracts: require('./Contracts'),
    Constants: require('./Constants'),
    // Chats: require('./Chats'),
    Clauses: require('./Clauses'),
    Categories: require('./Categories'),
    ContractDocumentaries: require('./ContractDocumentaries'),
    Emails: require('./Emails'),
    Events: require('./Events'),
    Firms: require('./Firms'),
    Memories: require('./Memories'),
    PersonIds: require('./PersonIds'),
    Notifications: require('./Notifications'),
    NDAs: require('./NDAs'),
    Offers: require('./Offers'),
    OffersUrlOTP: require('./OffersUrlOTP'),
    Offices: require('./Offices'),
    OfferDocumentAttachments: require('./OfferDocumentAttachments'),
    OfferDocuments: require('./OfferDocuments'),
    OfferEvents: require('./OfferEvents'),
    Persons: require('./Persons'),
    Properties: require('./Properties'),
    PropertiesImages: require('./PropertiesImages'),
    Phones: require('./Phones'),
    Roles: require('./Roles'),
    Reminders: require('./Reminders'),
    Ratings: require('./Ratings'),
    Urls: require('./Urls'),
    DocsAndClauses: require("./DocsAndClauses"),
    Notes: require("./Notes")
};
